---
- name: Install Radicale Debian package (creates user and config folders)
  apt: name="{{item}}" state=present
  with_items:
    - radicale
  become: true

- name: Install Radicale Python module
  pip:
    name: radicale
    state: latest
    executable: /usr/bin/pip3
  become: true

- name: Copy radicale config
  template:
    src: templates/etc/radicale/config.j2
    dest: /etc/radicale/config
    owner: root
    group: root
    mode: 0644
  become: true

- name: Creates radicale collection directory
  file:
    path: "{{ radicale_filesystem_folder }}"
    state: directory
    owner: radicale
    group: radicale
    mode: 0770
  become: true

- name: Create rights file
  template:
    src: templates/etc/radicale/rights.j2
    dest: "{{ radicale_rights_file }}"
    owner: root
    group: radicale
    mode: 0640
  become: true

- name: Create Radicale systemd service
  template:
    src: templates/etc/systemd/system/radicale.service.j2
    dest: /etc/systemd/system/radicale.service
    owner: root
    group: radicale
    mode: 0640
  become: true

- name: Creates directories for shared collections
  file:
    path: "{{ radicale_collection_root }}/{{item}}"
    state: directory
    owner: radicale
    group: radicale
    mode: 0750
  with_items:
    - "{{ radicale_shared_calendar_collection_name }}"
    - "{{ radicale_shared_contacts_collection_name }}"
  become: true

- name: Create shared collections property file
  template:
    src: "templates/var/lib/radicale/{{ item }}/.Radicale.props.j2"
    dest: "{{ radicale_collection_root }}/{{ item }}/.Radicale.props"
    mode: 0660
    owner: radicale
    group: radicale
    force: no
  with_items:
    - "{{ radicale_shared_calendar_collection_name }}"
    - "{{ radicale_shared_contacts_collection_name }}"
  become: true

- name:  Create symlink to shared calendar
  file:
    src: "{{ radicale_collection_root }}/{{ radicale_shared_calendar_collection_name }}"
    dest: "{{ radicale_collection_root }}/{{ item.name }}/{{ radicale_shared_calendar_collection_name }}"
    state: link
  with_items: "{{ radicale_users }}"
  become: true

- name:  Create symlink to shared contacts
  file:
    src: "{{ radicale_collection_root }}/{{ radicale_shared_contacts_collection_name }}"
    dest: "{{ radicale_collection_root }}/{{ item.name }}/{{ radicale_shared_contacts_collection_name }}"
    state: link
  with_items: "{{ radicale_users }}"
  become: true

- name: Initialize Git repository in collections
  command: "git init {{ radicale_filesystem_folder }}"
  become: true
  become_user: radicale

- name: Create gitignore file in Radicale collections directory
  template:
    src: templates/var/lib/radicale/.gitignore.j2
    dest: "{{ radicale_filesystem_folder}}/.gitignore"
    owner: root
    group: radicale
    mode: 0640
  become: true
